import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Phase 8 — test artifact dirs (generated by vitest coverage +
    // playwright reporter). Same directories are in .gitignore but
    // eslint scans cwd by default.
    "coverage/**",
    "playwright-report/**",
    "test-results/**",
    // Phase 11 — local-only triage scripts that walk the CUVET hospital
    // dump. Live under scratch/ (gitignored) so they never reach the
    // production lint surface. Re-exclude here so they don't show up in
    // `npm run lint` output either.
    "scratch/**",
  ]),
]);

export default eslintConfig;
